import 'ai_workbench.dart';

final aiWorkbenchMockSnapshot = AiWorkbenchSnapshot.fromJson({
  'schemaVersion': 1,
  'generatedAt': '2026-05-28T00:00:00.000Z',
  'providers': [
    {
      'id': 'terminal',
      'name': '终端',
      'transport': 'desktop-signal',
      'capabilities': [
        'project-list',
        'session-list',
        'session-read',
        'stdin-send',
        'quick-actions',
        'screen-render',
      ],
    },
    {
      'id': 'codex',
      'name': 'Codex',
      'transport': 'app-server',
      'capabilities': [
        'project-list',
        'conversation-list',
        'conversation-read',
        'conversation-create',
        'conversation-rename',
        'conversation-archive',
        'message-send',
        'turn-cancel',
        'model-list',
        'config-read',
        'config-write',
        'event-stream',
      ],
    },
  ],
  'projects': [
    {
      'id': r'terminal:F:\Download\GitHub\YiboVibe',
      'providerId': 'terminal',
      'name': 'YiboVibe',
      'path': r'F:\Download\GitHub\YiboVibe',
      'conversationIds': ['terminal-1', 'terminal-2', 'terminal-3'],
      'branches': ['main'],
      'originUrl': 'https://github.com/datouluobo/YiboVibe.git',
      'updatedAt': 1779955240,
    },
    {
      'id': r'terminal:F:\Download\GitHub\YiboVibe\server',
      'providerId': 'terminal',
      'name': 'server',
      'path': r'F:\Download\GitHub\YiboVibe\server',
      'conversationIds': ['terminal-4'],
      'branches': ['main'],
      'originUrl': 'https://github.com/datouluobo/YiboVibe.git',
      'updatedAt': 1779955100,
    },
    {
      'id': r'codex:F:\Download\GitHub\YiboVibe',
      'providerId': 'codex',
      'name': 'YiboVibe',
      'path': r'F:\Download\GitHub\YiboVibe',
      'conversationIds': ['thread-1', 'thread-2', 'thread-3'],
      'branches': ['codex/test-codex-app-server-mvp'],
      'originUrl': 'https://github.com/datouluobo/YiboVibe.git',
      'updatedAt': 1779955200,
    },
    {
      'id': r'codex:F:\Download\GitHub\Ooitech',
      'providerId': 'codex',
      'name': 'Ooitech',
      'path': r'F:\Download\GitHub\Ooitech',
      'conversationIds': ['thread-4'],
      'branches': ['main'],
      'originUrl': 'https://github.com/datouluobo/Ooitech.git',
      'updatedAt': 1779955000,
    },
    {
      'id': r'codex:F:\Download\GitHub\YiboClock',
      'providerId': 'codex',
      'name': 'YiboClock',
      'path': r'F:\Download\GitHub\YiboClock',
      'conversationIds': [],
      'branches': ['main'],
      'originUrl': 'https://github.com/datouluobo/YiboClock.git',
      'updatedAt': 1779953000,
    },
  ],
  'conversations': [
    {
      'id': 'terminal-1',
      'providerId': 'terminal',
      'projectId': r'terminal:F:\Download\GitHub\YiboVibe',
      'title': 'wsl #2',
      'preview': 'flutter test 正在等待下一条输出',
      'cwd': r'F:\Download\GitHub\YiboVibe\mobile\android',
      'source': 'wsl',
      'status': 'running',
      'gitInfo': {
        'branch': 'main',
        'originUrl': 'https://github.com/datouluobo/YiboVibe.git',
      },
      'createdAt': 1779951200,
      'updatedAt': 1779955240,
    },
    {
      'id': 'terminal-2',
      'providerId': 'terminal',
      'projectId': r'terminal:F:\Download\GitHub\YiboVibe',
      'title': 'pwsh #1',
      'preview': '最近执行 cargo check -p tauri-app',
      'cwd': r'F:\Download\GitHub\YiboVibe',
      'source': 'pwsh',
      'status': 'idle',
      'updatedAt': 1779955000,
    },
    {
      'id': 'terminal-3',
      'providerId': 'terminal',
      'projectId': r'terminal:F:\Download\GitHub\YiboVibe',
      'title': 'cmd #1',
      'preview': '等待输入路径',
      'cwd': r'F:\Download\GitHub\YiboVibe',
      'source': 'cmd',
      'status': 'waitingApproval',
      'updatedAt': 1779954900,
    },
    {
      'id': 'terminal-4',
      'providerId': 'terminal',
      'projectId': r'terminal:F:\Download\GitHub\YiboVibe\server',
      'title': 'pwsh #2',
      'preview': 'go test ./... 已完成',
      'cwd': r'F:\Download\GitHub\YiboVibe\server',
      'source': 'pwsh',
      'status': 'idle',
      'updatedAt': 1779954800,
    },
    {
      'id': 'thread-1',
      'providerId': 'codex',
      'projectId': r'codex:F:\Download\GitHub\YiboVibe',
      'title': '开始实现移动端',
      'preview': '移动端 AI 工作台布局推进中',
      'cwd': r'F:\Download\GitHub\YiboVibe',
      'source': 'vscode',
      'cliVersion': '0.133.0-alpha.1',
      'status': 'running',
      'gitInfo': {
        'branch': 'codex/test-codex-app-server-mvp',
        'originUrl': 'https://github.com/datouluobo/YiboVibe.git',
      },
      'createdAt': 1779951600,
      'updatedAt': 1779955200,
    },
    {
      'id': 'thread-2',
      'providerId': 'codex',
      'projectId': r'codex:F:\Download\GitHub\YiboVibe',
      'title': '新建测试分支验证方案',
      'preview': '拆出验证分支并确认影响范围',
      'cwd': r'F:\Download\GitHub\YiboVibe',
      'source': 'vscode',
      'status': 'idle',
      'updatedAt': 1779955100,
    },
    {
      'id': 'thread-3',
      'providerId': 'codex',
      'projectId': r'codex:F:\Download\GitHub\YiboVibe',
      'title': '控制Codex方案',
      'preview': '收敛移动端交互和工具隔离策略',
      'cwd': r'F:\Download\GitHub\YiboVibe',
      'source': 'vscode',
      'status': 'idle',
      'updatedAt': 1779955100,
    },
    {
      'id': 'thread-4',
      'providerId': 'codex',
      'projectId': r'codex:F:\Download\GitHub\Ooitech',
      'title': '分析项目找BUG与改进点',
      'preview': '整理核心缺陷和修复优先级',
      'cwd': r'F:\Download\GitHub\Ooitech',
      'source': 'vscode',
      'status': 'idle',
      'updatedAt': 1779955000,
    },
    {
      'id': 'thread-5',
      'providerId': 'codex',
      'title': '安装 Chrome 插件',
      'preview': '处理浏览器插件安装流程',
      'cwd': r'F:\Download\GitHub\YiboVibe',
      'source': 'vscode',
      'status': 'idle',
      'updatedAt': 1779954200,
    },
  ],
  'activeConversationId': 'thread-1',
  'messagesByConversationId': {
    'terminal-1': [
      {
        'id': 'terminal-1:output:0',
        'providerId': 'terminal',
        'conversationId': 'terminal-1',
        'role': 'terminal',
        'title': '输出',
        'text': r'$ cd /mnt/f/Download/GitHub/YiboVibe/mobile/android',
      },
      {
        'id': 'terminal-1:output:1',
        'providerId': 'terminal',
        'conversationId': 'terminal-1',
        'role': 'terminal',
        'title': '输出',
        'text': r'$ flutter test',
      },
      {
        'id': 'terminal-1:output:2',
        'providerId': 'terminal',
        'conversationId': 'terminal-1',
        'role': 'terminal',
        'title': '输出',
        'text': '00:03 +4: loading test/widget_test.dart',
      },
    ],
    'terminal-2': [
      {
        'id': 'terminal-2:output:0',
        'providerId': 'terminal',
        'conversationId': 'terminal-2',
        'role': 'terminal',
        'title': '输出',
        'text': r'PS F:\Download\GitHub\YiboVibe> cargo check -p tauri-app',
      },
    ],
    'terminal-3': [
      {
        'id': 'terminal-3:output:0',
        'providerId': 'terminal',
        'conversationId': 'terminal-3',
        'role': 'terminal',
        'title': '输出',
        'text': 'Enter path:',
      },
    ],
    'terminal-4': [
      {
        'id': 'terminal-4:output:0',
        'providerId': 'terminal',
        'conversationId': 'terminal-4',
        'role': 'terminal',
        'title': '输出',
        'text': r'PS F:\Download\GitHub\YiboVibe\server> go test ./...',
      },
      {
        'id': 'terminal-4:output:1',
        'providerId': 'terminal',
        'conversationId': 'terminal-4',
        'role': 'terminal',
        'title': '输出',
        'text': 'ok   yibovibe/server/internal/service',
      },
    ],
    'thread-1': [
      {
        'id': 'thread-1:user:0',
        'providerId': 'codex',
        'conversationId': 'thread-1',
        'role': 'user',
        'title': '用户',
        'text': '根据 mobile-ai-workbench-ui-plan-2026-05-28.md 开始完成移动端',
      },
      {
        'id': 'thread-1:assistant:1',
        'providerId': 'codex',
        'conversationId': 'thread-1',
        'role': 'assistant',
        'title': 'Codex',
        'text': '已经开始改移动端工作台，先收工具、项目、会话三层结构。',
      },
      {
        'id': 'thread-1:user:2',
        'providerId': 'codex',
        'conversationId': 'thread-1',
        'role': 'user',
        'title': '用户',
        'text': '再次尝试拉起测试',
      },
      {
        'id': 'thread-1:assistant:3',
        'providerId': 'codex',
        'conversationId': 'thread-1',
        'role': 'assistant',
        'title': 'Codex',
        'text': '已再次拉起测试，当前改用模拟器路径继续验证，不再卡在 Flutter Web 首帧。',
      },
      {
        'id': 'thread-1:user:4',
        'providerId': 'codex',
        'conversationId': 'thread-1',
        'role': 'user',
        'title': '用户',
        'text': '进来了，但这好像是旧版本啊，和刚才在 web 看到的不一样',
      },
      {
        'id': 'thread-1:assistant:5',
        'providerId': 'codex',
        'conversationId': 'thread-1',
        'role': 'assistant',
        'title': 'Codex',
        'text': '问题已经定位，登录成功后的默认入口还在旧 ConsolePage，我把默认首页切到了新的 AiWorkbenchPage。',
      },
      {
        'id': 'thread-1:user:6',
        'providerId': 'codex',
        'conversationId': 'thread-1',
        'role': 'user',
        'title': '用户',
        'text': '重新调下布局，有些侧边的可以收起',
      },
      {
        'id': 'thread-1:assistant:7',
        'providerId': 'codex',
        'conversationId': 'thread-1',
        'role': 'assistant',
        'title': 'Codex',
        'text': '已把会话页改成移动端单列结构，左侧常驻栏收成点击展开的会话切换条。',
      },
      {
        'id': 'thread-1:user:8',
        'providerId': 'codex',
        'conversationId': 'thread-1',
        'role': 'user',
        'title': '用户',
        'text': '会话列表对了，但是具体的会话不对，当前这种会话里应该有很多条互相的对话',
      },
      {
        'id': 'thread-1:assistant:9',
        'providerId': 'codex',
        'conversationId': 'thread-1',
        'role': 'assistant',
        'title': 'Codex',
        'text':
            '收到，这不是会话列表问题，而是当前线程正文还停留在极简 mock。我正在把当前 Codex 会话补成长对话流，让消息区和滚动行为更接近真实使用。',
      },
    ],
    'thread-2': [
      {
        'id': 'thread-2:user:0',
        'providerId': 'codex',
        'conversationId': 'thread-2',
        'role': 'user',
        'title': '用户',
        'text': '新建测试分支，验证移动端 UI 方案是否需要单独隔离',
      },
    ],
    'thread-3': [
      {
        'id': 'thread-3:user:0',
        'providerId': 'codex',
        'conversationId': 'thread-3',
        'role': 'user',
        'title': '用户',
        'text': '整理一个控制 Codex 的移动端交互方案',
      },
    ],
    'thread-4': [
      {
        'id': 'thread-4:user:0',
        'providerId': 'codex',
        'conversationId': 'thread-4',
        'role': 'user',
        'title': '用户',
        'text': '分析项目找 BUG 与改进点，按优先级给出建议',
      },
    ],
    'thread-5': [
      {
        'id': 'thread-5:user:0',
        'providerId': 'codex',
        'conversationId': 'thread-5',
        'role': 'user',
        'title': '用户',
        'text': '安装 Chrome 插件并记录验证过程',
      },
    ],
  },
  'modelsByProviderId': {
    'terminal': [],
    'codex': [
      {
        'id': 'gpt-5.5',
        'providerId': 'codex',
        'label': 'GPT-5.5',
        'isDefault': true,
        'defaultReasoningEffort': 'medium',
        'supportedReasoningEfforts': ['minimal', 'low', 'medium', 'high'],
      },
    ],
  },
  'configsByProviderId': {
    'terminal': {
      'providerId': 'terminal',
      'cwd': r'F:\Download\GitHub\YiboVibe',
    },
    'codex': {
      'providerId': 'codex',
      'model': 'gpt-5.5',
      'modelProvider': 'chatgpt',
      'approvalPolicy': 'on-request',
      'sandboxMode': 'workspace-write',
    },
  },
  'errors': [],
});
